### ISSUE TITLE
Setup Travis for CI

### ISSUE THREAD

**Issue by deweydell** [WriteSpeakCode/writespeakcode.com#14]
### Description

Create a `travis.yml` file which runs our CI before deploying the site on PRs and master branches. 

**Why this is valuable:**

This will help developers make sure they pass all tests and linting before the site is deployed.

### Acceptance Criteria

- [ ] Prettier and flow are run in checks
- [ ] Checks are run before deployment
- [ ] Status of checks show up in github
- [ ] Travis build badge is present in readme

**Comment by lynncyrin** [comment]
👋  I wanna handle this one!

**Comment by lynncyrin** [comment]
Relevant information here, is that netlify has specific docs about ci https://www.netlify.com/docs/continuous-deployment/
