### ISSUE TITLE
Retaining women in open source: Organising open source day monthly

### ISSUE THREAD

**Issue by tapaswenipathak** [WriteSpeakCode/writespeakcode.com#142]
Hi folks: Finding an active open source contributor or maintainer woman is hard. Internships give a break in open source, if observed there is no retention of women in open source and research[1] suggests. Implementing open source day per month letting woman work with mentor and contribute in an open source project they would like would be practical implementation than just publishing research and articles. Lemme know if you would interested in supporting and I will share further things.

[1] https://en.wikipedia.org/wiki/Diversity_in_open-source_software

**Comment by coilysiren** [comment]
This is a non-traditional github issue ^^ @tapaswenipathak can you email me with any more detail you have here? `lynncyrin+writespeakcode@gmail.com`

**Comment by tapaswenipathak** [comment]
On Thu, 29 Aug 2019, 09:08 lynncyrin, <notifications@github.com> wrote:

> This is a non-traditional github issue ^^ @tapaswenipathak
> <https://github.com/tapaswenipathak> can you email me with any more
> detail you have here? lynncyrin+writespeakcode@gmail.com
>
Hey, I will email the proposal out, thanks.
